services:
  postgres:
    image: pgvector/pgvector:pg16      # Postgres 16 já com a extensão vector
    environment:
      POSTGRES_DB: cineverse
      POSTGRES_USER: cineverse
      POSTGRES_PASSWORD: cineverse
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pgdata:
